# Generated by Django 3.2 on 2023-05-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCaseForSEA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('case_name', models.CharField(blank=True, max_length=1, null=True, verbose_name='用例名称')),
                ('step', models.TextField(blank=True, null=True, verbose_name='操作步骤')),
                ('status', models.IntegerField(blank=True, default=0, help_text='0:表示有效，1:表示无效，用于软删除', null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.CharField(blank=True, max_length=20, null=True, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '测试用例表',
                'verbose_name_plural': '测试用例表',
                'db_table': 'sea_test_case',
            },
        ),
    ]
