# Generated by Django 3.2 on 2023-06-14 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selenium_apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcaseforsea',
            name='step',
        ),
        migrations.AlterField(
            model_name='testcaseforsea',
            name='case_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='用例名称'),
        ),
        migrations.CreateModel(
            name='TestCaseSteps',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('LocationPath', models.CharField(blank=True, max_length=256, null=True, verbose_name='定位路径')),
                ('Method', models.CharField(blank=True, max_length=256, null=True, verbose_name='方法|操作')),
                ('Parameter', models.CharField(blank=True, max_length=256, null=True, verbose_name='传入参数')),
                ('Action', models.CharField(blank=True, max_length=256, null=True, verbose_name='步骤动作')),
                ('Expected', models.CharField(blank=True, max_length=256, null=True, verbose_name='预期结果')),
                ('status', models.IntegerField(blank=True, default=0, help_text='0:表示有效，1:表示无效，用于软删除', null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('testcaseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selenium_apps.testcaseforsea', verbose_name='所属用例')),
            ],
            options={
                'verbose_name': '用例步骤表',
                'verbose_name_plural': '用例步骤表',
                'db_table': 'sea_test_case_steps',
            },
        ),
    ]
