# Generated by Django 3.2 on 2023-07-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selenium_apps', '0002_auto_20230614_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcaseforsea',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
    ]
