# Generated by Django 3.2 on 2023-07-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selenium_apps', '0003_testcaseforsea_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcaseforsea',
            name='length',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='步长'),
        ),
    ]
