# Generated by Django 3.2 on 2023-07-26 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_platform', '0006_alter_testsuite_type'),
        ('selenium_apps', '0004_testcaseforsea_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case2SuiteForSEA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(blank=True, default=0, help_text='0：有效，1：无效', null=True, verbose_name='是否有效')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selenium_apps.testcaseforsea', verbose_name='测试用例')),
                ('test_suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_platform.testsuite', verbose_name='用例集合')),
            ],
            options={
                'verbose_name': '用例集中添加用例表',
                'verbose_name_plural': '用例集中添加用例表',
                'db_table': 'sea_case_2_suite',
            },
        ),
    ]
