# Generated by Django 3.2 on 2023-08-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selenium_apps', '0006_testcaseexecuteresultforsea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcaseexecuteresultforsea',
            name='request_data',
        ),
        migrations.AddField(
            model_name='testcaseexecuteresultforsea',
            name='length',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='步长'),
        ),
    ]
