# Generated by Django 3.2 on 2023-09-01 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selenium_apps', '0007_auto_20230824_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case2SuiteExecuteResultForSEA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('belong_test_suite_exe', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.IntegerField(blank=True, help_text='0：表示未执行，1：表示已执行', null=True)),
                ('length', models.IntegerField(blank=True, default=0, null=True, verbose_name='步长')),
                ('execute_result', models.CharField(blank=True, max_length=1024, null=True, verbose_name='执行结果')),
                ('exception_info', models.CharField(blank=True, max_length=2048, null=True)),
                ('execute_total_time', models.CharField(blank=True, max_length=300, null=True, verbose_name='执行总计耗时')),
                ('execute_start_time', models.CharField(blank=True, max_length=300, null=True, verbose_name='执行开始时间')),
                ('execute_end_time', models.CharField(blank=True, max_length=300, null=True, verbose_name='执行结束时间')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('belong_test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selenium_apps.testcaseforsea', verbose_name='所属用例')),
            ],
            options={
                'verbose_name': '用例执行结果记录表',
                'verbose_name_plural': '用例执行结果记录表',
                'db_table': 'sea_case2suite_execute_result',
            },
        ),
    ]
