# Generated by Django 3.2 on 2024-04-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('case_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='用例名称')),
                ('request_data', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='请求数据')),
                ('uri', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='接口地址')),
                ('maintainer', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='编写人员')),
                ('request_method', models.CharField(blank=True, max_length=128, null=True, verbose_name='请求方式')),
                ('status', models.IntegerField(blank=True, default=0, help_text='0:表示有效，1:表示无效，用于软删除', null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '测试用例表',
                'verbose_name_plural': '测试用例表',
                'db_table': 'loc_test_case',
            },
        ),
    ]
