# Generated by Django 3.2 on 2024-04-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locust_apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='test_method',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='测试方式'),
        ),
    ]
