# Generated by Django 3.2 on 2024-04-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locust_apps', '0002_testcase_test_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='test_method',
        ),
        migrations.AddField(
            model_name='testcase',
            name='test_r',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='每秒启动数'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='test_t',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='持续时间'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='test_u',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='模拟用户数'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='test_wait',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='等待时间'),
        ),
    ]
