# Generated by Django 3.2 on 2024-04-19 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locust_apps', '0003_auto_20240410_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='test_r',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='test_t',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='test_u',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='test_wait',
        ),
    ]
