# Generated by Django 3.2 on 2024-05-22 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_platform', '0012_alter_testsuite_type'),
        ('locust_apps', '0005_testcase_assert_key'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestCase',
            new_name='LocTestCase',
        ),
        migrations.CreateModel(
            name='AddLocCase2Suite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(blank=True, default=0, help_text='0：有效，1：无效', null=True, verbose_name='是否有效')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locust_apps.loctestcase', verbose_name='测试用例')),
                ('test_suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_platform.testsuite', verbose_name='用例集合')),
            ],
            options={
                'verbose_name': '用例集中添加用例表',
                'verbose_name_plural': '用例集中添加用例表',
                'db_table': 'loc_add_case_into_suite',
            },
        ),
    ]
