# Generated by Django 3.2 on 2023-05-27 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_platform', '0002_testcaseforsea'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestCaseForSEA',
        ),
    ]
