# Generated by Django 3.2 on 2024-02-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_platform', '0008_alter_uploadscasetemplate_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='用户名')),
                ('password', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='密码')),
                ('login_time', models.DateTimeField(auto_now_add=True, verbose_name='登录时间')),
            ],
            options={
                'verbose_name': '用户登录记录表',
                'verbose_name_plural': '用户登录记录表',
                'db_table': 'atp_userlog',
            },
        ),
    ]
