# Generated by Django 3.2 on 2024-02-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_platform', '0009_userlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='密码'),
        ),
    ]
